---
- name: install packages required to build kea
  apt:
    name:
      - clang
      - automake
      - make
      - pkg-config
      - libbotan1.10-dev
      - libboost1.62-all-dev
      - liblog4cplus-dev
    state: present

- name: copy kea services
  copy:
    src: '{{ item }}.service'
    dest: '{{ systemdDir }}'
  loop:
    - kea-dhcp-ddns
    - kea-dhcp4

- name: ensure prerequired directories for kea to function
  file:
    path: '{{ item }}'
    owner: root
    group: staff
    state: directory
  loop:
    - '{{ keaEtcDir }}'

- name: copy kea config
  copy:
    src: '{{ item }}'
    dest: '{{ keaEtcDir }}/{{ item }}'
  loop:
    - kea-ctrl-agent.conf
    - kea-dhcp-ddns.conf
    - kea-dhcp4.conf
    - kea-dhcp6.conf
    - keactrl.conf

- name: actuall install kea
  block:
    - name: download kea archive
      get_url:
        url: https://downloads.isc.org/isc/kea/{{ keaVersion }}/kea-{{ keaVersion }}.tar.gz
        dest: '{{ keaPrefix }}/src'
    - unarchive:
        src: '{{ keaPrefix }}/src/kea-{{ keaVersion }}.tar.gz'
        dest: '{{ keaPrefix }}/src'
        remote_src: yes
    - name: remove downloaded file
      file:
        path: '{{ keaSrcDir }}.tar.gz'
        state: absent
    - name: make clean
      make:
        chdir: '{{ keaSrcDir }}'
        target: clean
    - name: ./configure
      raw: cd {{ keaSrcDir }} && sudo ./configure --prefix=/usr/local --enable-shell --with-site-packages=/usr/lib/python3/dist-packages
    - name: make
      make:
        chdir: '{{ keaSrcDir }}'
    - name: make install
      make:
        chdir: '{{ keaSrcDir }}'
        target: install
      notify:
        - restart kea-dhcp-ddns
        - restart kea-dhcp4
  when: installKea | bool
