---
- name: install packages required to build kea
  apt:
    name:
      - clang
      - automake
      - make
      - pkg-config
      - libbotan1.10-dev
      - libboost1.62-all-dev
      - liblog4cplus-dev
    state: present

- name: copy kea services
  copy:
    src: '{{ item }}.service'
    dest: '{{ systemdDir }}'
  loop:
    - kea-dhcp-ddns
    - kea-dhcp4

- name: copy kea config
  copy:
    src: '{{ item }}'
    dest: '{{ keaEtcDir }}'
  loop:
    - kea-ctrl-agent.conf
    - kea-dhcp-ddns.conf
    - kea-dhcp4.conf
    - kea-dhcp6.conf
    - keactrl.conf
  notify:
    - restart kea-dhcp-ddns
    - restart kea-dhcp4
