---
- name: apt package housekeeping
  become: true
  block:
    - name: update cache
      apt:
        update_cache: yes
    - name: remove unneeded dependencies
      apt:
        autoremove: yes

- name: setup network
  become: true
  block:
    - name: copy templated /etc/netplan config
      template:
        src: 80-network.yaml.j2
        dest: /etc/netplan
        owner: root
        group: root
        mode: '0644'

    - name: set hostname
      hostname:
        name: foundation

    - name: copy templated /etc/hosts config
      template:
        src: hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'

- name: setup sshd
  become: true
  block:
    - name: add public key to authorized_keys
      authorized_key:
        user: ops
        key: "{{ lookup('file', 'foundation.key.pub') }}"
        state: present

    - name: copy sshd config
      copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'

    - name: enable sshd with systemd
      systemd:
        name: ssh
        enabled: true
