---
# remember renaming or changing the `containers` member name can
# cause scripts in other parts of this repo to break (not just
# current ansible directory)
imageName: debian-base-custom
profileName: foundation-profile
containerNamePrefix: foundation-
containers:
  - name: primary
    static: confirmed
    address: '10.0.0.4/16'
    gateway: '10.0.0.1'
    dnsNameservers: '1.1.1.1'
  - name: secondary
  - name: tertiary
