---
- name: configure dhcp ordinal hosts
  become: true
  gather_facts: true
  hosts: dhcp:&dns
  roles:
    - role: common
      tags: common
    - role: dns
      tags: dns
    - role: dhcp
      tags: dhcp
    - role: dns
      tags: dns
- name: configure dynamic ordinal hosts
  become: true
  gather_facts: true
  hosts: dynamic
  roles:
    - role: common
      tags: common
