---
- name: wait for ssh
  hosts: all
  gather_facts: false
  tasks:
    - name: "wait for ssh for 300 seconds"
      wait_for_connection:
        delay: 15
        timeout: 300
        connect_timeout: 10
        sleep: 5
- name: configure base image
  hosts: all
  gather_facts: true
  roles:
    - common
