---
# other packages are defined in
# distrobuilder/distrobuilder.yaml
- name: apt housekeeping
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    upgrade: safe

- name: install convenience packages
  apt:
    name:
      - curl
    state: present
