---
# - name: debug opsPassword
#   debug:
#     var: opsPassword

# - name: debug rootPassword
#   debug:
#     var: rootPassword

- name: change ops user password
  user:
    name: ops
    comment: ops
    password: '{{ opsPassword }}'
    append: yes
    groups:
      - ops
    state: present
  when: opsPassword is defined and opsPassword != ''

- name: change root password
  user:
    name: root
    password: '{{ rootPassword }}'
    append: yes
    groups:
      - root
    state: present
  when: rootPassword is defined and rootPassword != ''
