---
- name: restart kea-dhcp-ddns
  systemd:
    name: kea-dhcp-ddns
    state: restarted
    daemon_reload: true

- name: restart kea-dhcp4
  systemd:
    name: kea-dhcp4
    state: restarted
    daemon_reload: true
