---
- name: restart kea-dhcp-ddns
  systemd:
    name: kea-dhcp-ddns
    state: restarted
    daemon_reload: true

- name: restart kea-dhcp4
  systemd:
    name: kea-dhcp4
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: restart named
  systemd:
    name: named
    enabled: yes
    state: restarted
    daemon_reload: yes
