---
# this rsync's resources required for making an lxc image to `foundation`
# and imports it to lxc

- name: install rsync
  apt:
    name: rsync
    state: present

- name: copy distrobuilder files
  synchronize:
    src: ./
    dest: '{{ imageArtifacts }}'
    copy_links: yes
    recursive: yes
    delete: yes

