---
- name: install packages required to build bind9 (named)
  apt:
    name:
      - clang
      - automake
      - make
      - pkg-config
      - python3-ply
      - libuv1-dev
      - libjson-c-dev
      - libcap-dev
      - zlibc
      - libxml2-dev

- name: create bind user
  import_tasks: user.yml

- name: copy bind9 systemd service
  copy:
    src: named.service
    dest: '{{ systemdDir }}'

- name: ensure prerequired directories for bind to function
  block:
    - name: files with named / named ownership
      file:
        path: '{{ item }}'
        owner: named
        group: named
        state: directory
      loop:
        - '{{ bindEtcDir }}/zones'
        - '{{ bindCacheDir }}'
        - '{{ bindLogDir }}'
        - '{{ bindRunDir }}'
    - name: files with root / staff ownership
      file:
        path: '{{ item }}'
        owner: root
        group: staff
      loop:
        - '{{ bindPrefix }}/var/cache'
        - '{{ bindPrefix }}/var/log'

- name: create rndc.key
  command: rndc-confgen -a

- name: copy all bind config
  block:
    - name: copy bind config
      copy:
        src: '{{ item }}'
        dest: '{{ bindEtcDir }}'
        owner: named
        group: named
      loop:
        - named.conf
        - named.log.conf
    - name: copy bind zones
      copy:
        src: '{{ item }}'
        owner: named
        group: named
        dest: '{{ bindEtcDir }}/zones/{{ item }}'
      loop:
        - dev.kofler.internal.local.dynamic.zone
        - dev.kofler.internal.local.test.zone
        - dev.kofler.internal.local.zone
        - dev.kofler.internal.test.zone
      notify:
        - restart named
        - restart kea-dhcp-ddns
