---
- name: create named group
  group:
    name: named
    state: present

- name: create named user
  user:
    name: named
    group: named
    create_home: no
    comment: for bind9
    state: present
