---
- name: create named group
  group:
    name: '{{ bindUser }}'
    state: present

- name: create named user
  user:
    name: '{{ bindUser }}'
    group: '{{ bindUser }}'
    create_home: no
    comment: for bind9
    state: present
