---
- name: wait for ssh
  hosts: all
  gather_facts: false
  tasks:
    - name: "wait for ssh for 60 seconds"
      wait_for_connection:
        delay: 15
        timeout: 60
        connect_timeout: 10
        sleep: 5
- name: configure base image
  hosts: all
  gather_facts: true
  vars:
    ipv4Cidr: '10.0.0.2/8'
    hostname: foundation
    domainName: local.internal.kofler.dev
  roles:
    - common
