---
- name: install bridge-utils
  apt:
    name: bridge-utils
    state: present

- name: add network bridge
  blockinfile:
    path: /etc/network/interfaces
    state: present
    block: "{{ lookup('template', 'interfaces.part.j2') }}"
#
# reboot performed in 'final' task
# - name: reboot
#   reboot:
#     connect_timeout: 20
#     msg: reboot initiated by ansible
#     reboot_timeout: 3000
